### ISSUE TITLE
Shutdown github pages

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#132]
As gh-pages don't allow us to setup redirect and rewrite rules (#117), we are switching to a new deployment environment, which is for now Netlify (#130).
During a testing phase, we are publishing to both gh-pages and Netlify, but once we will be confident with the new solution (if netlify is not ok, we have alternatives), we will drop gh-pages.
The current way we use gh-pages also has a major drawback: it makes the repository size grow very fast (the whole documentation site size is around 500Mb) because we store the published html assets in the `gh-pages` branch of the documentation site configuration repository.
This is a pain for developers and slows down the clone/fetch operations when not configuring them to ignore the gh-pages branch (this requires extra config after the repo is locally cloned).
So removing the branch will make our life easier as well.

### Proposed tasks
- [x] ensure that the DocSearch configuration don't use the gh-pages url anymore. :warning: about the url, see the CNAME related issue #118. Done with https://github.com/algolia/docsearch-configs/pull/3642
- [x] disable push to the `gh-pages` branch. See #146
- [x] disable gh-pages in the repository
  - https://docs.github.com/en/github/working-with-github-pages/unpublishing-a-github-pages-site#unpublishing-a-user-or-organization-site
  - **WARN**: the https://bonitasoft.github.io/ site won't be available anymore
  - remove the `gh-pages` branch. We will loose the deployment history and the generated content changes but the repo size will decrease a lot
- [x] antora playbook: no need for the noJekyll file generation (to be confirmed). See #164
- [x] remove reference to gh-pages in the repository (see #164) and open issue and update them

**Comment by tbouffard** [comment]
All tasks have been managed, so closing.
