### ISSUE TITLE
Prepare github-pages publish

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#23]
We are going to published the generated static sites to GitHub pages.
We can start doing this prior configuring automation with #5 

- [x] ensure noJekyll, see https://docs.antora.org/antora/2.3/publish-to-github-pages/#use-the-supplemental-ui --> #26 
- [x] robots disallowed, see #19 
- [x] sitemap configuration review
- [x] urls without html extension review
- [x] setup gh-pages branch: orphan branch created and configured as protected, initial index.html created
- [x] 1st manual push of the generated site to gh-pages to make a 1st version of the site available at https://bonitasoft.github.io/. Once #17 and #26 have been merged

**Comment by tbouffard** [comment]
No more 404 error but very nice home page!

![image](https://user-images.githubusercontent.com/27200110/99765542-946b0200-2aff-11eb-887d-cbd6861b2a3a.png)

**Comment by tbouffard** [comment]
Manual push done, actions 
- build locally the master branch: `npm run build`
- commit the generated doc site to the `gh-pages`
- push the `gh-pages` to remote: ba976f42865c111fe183256f3c920a4fa69bc3a6
