### ISSUE TITLE
Add support for asciinema

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#29]
### Information and conversion procedure from previous poc

The kramdoc tool is unable to convert asciinema content and generates error, for instance, with file like Bonita `migrate-from-an-earlier-version-of-bonita-bpm.md`
```javascript
<script type="text/javascript">
function loadCSS(filename){
    let file = document.createElement("link");
    file.setAttribute("rel", "stylesheet");
    file.setAttribute("type", "text/css");
    file.setAttribute("href", filename);
    document.head.appendChild(file);
}
loadCSS("./assets/asciinema-player.css");
</script>
<asciinema-player src="bonita/images/${varVersion}/case_overview_update_mode-ascii.cast" speed="2" theme="monokai" title="Update case overview console output example" cols="240" rows="32"></asciinema-player>
<script src="./assets/asciinema-player.js"></script>
```

Workaround for the conversion procedure
* prior migrating, comment the asciinema block in the md file
* convert to asciidoctor
* in the converted file, replaced the commented block (surrounded by '////'):
  * replace the `/` characters by `+` (you should have some `++++` at the end of the block a)
  * for more information, see https://asciidoctor.org/docs/user-manual/#pass-blocks (
* update the path to sources (js, css et .cast):
  * “./assets/asciinema-player.css” → "/_attachments/asciinema-player.css" 
  * “bonita/images/${varVersion}/case_overview_update_mode-ascii.cast” → “_images/images/case_overview_update_mode-ascii.cast” 
  * "./assets/asciinema-player.js" → "./_attachments/asciinema-player.js"
* create a new folder `modules/ROOT/assets/attachments` and copy the asciinema-player.js et asciinema-player.css that are currently only available in the private documentation site gnerator repository
* ensure that the ascinema source file (.cast extension) exist in the images folder: for instance, modules/ROOT/assets/images/images/case_overview_update_mode-ascii.cast

### Work to do

**New Investigations to be conducted**
- [ ] There is currently no Asciidoctor native support for asciinema, see https://github.com/asciidoctor/asciidoctor/issues/1798, let's see if there is some in Antora or if we can contribute one (maybe later)
- [ ] See if the asciinema attachments files can be made available through the antora-ui bundle (documentation theme) to avoid duplicate the asciinema resources in all repositories. This will also prepare the real integration when available

**Tasks** (to be extended depending on the chosen solution)
- [ ] document the solution in the content documentation conversion guide
- [ ] document the solution in the tech writer contributing guide to let user know how they can integrated asciinema resources in the doc site (see #52)
